POST http://localhost:3001/api/menuItems
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlZ3VsIiwiaWQiOjMsImlhdCI6MTc2NDMzMzU5NH0.b1EP9GaQmgNZR4VvL2b82rmkiJzo0QD6zhSWwzOiloU

{
  "name": "bread",
  "price": 20,
  "weight": 50
}