PUT http://localhost:3001/api/users/5
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvQGdtYWlsLmNvbSIsImlkIjozLCJpYXQiOjE3NjM0ODQyOTN9.b-mPQgrJd8walRwPjKsN1A0cTc3Ew9cd1PZKx83DuzY'

{
  "staff": true,
  "secret": "1"
}